import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedRectangle37Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/Generated20142018BachelorinComputerScienceWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedHithisisSarahIhavebecomeateachingassistanceonCSsincecol.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedUnknowngirl16Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedRectangle22Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedFocusWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedRectangle36Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedMain_Background2Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedUntitled_Artwork22Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedMain_Background2Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedEducationWidget2.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedNextWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedPurdueUniversityWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedSoftwareEngineerAmazonWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedMain_Background1Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedProgrammingWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedConnectWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedExperienceWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedEducationWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedSarahTWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedMain_Background1Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/Generated2019presentWidget.dart';

/* Frame mentor bio 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMentorbio2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 780.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -34.0,
                top: -69.0,
                right: null,
                bottom: null,
                width: 397.0,
                height: 933.0,
                child: GeneratedUntitled_Artwork22Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 506.0,
                child: GeneratedMain_Background1Widget(),
              ),
              Positioned(
                left: 228.0,
                top: 528.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 70.0,
                child: GeneratedRectangle34Widget(),
              ),
              Positioned(
                left: 197.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 71.0,
                child: GeneratedRectangle38Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 494.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 24.0,
                child: GeneratedFocusWidget(),
              ),
              Positioned(
                left: 52.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 20.0,
                child: GeneratedRectangle36Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 19.0,
                child: GeneratedProgrammingWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 506.0,
                child: GeneratedMain_Background2Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 20.0,
                child: GeneratedRectangle37Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 19.0,
                child: GeneratedEducationWidget1(),
              ),
              Positioned(
                left: 139.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 28.0,
                child: GeneratedSarahTWidget1(),
              ),
              Positioned(
                left: 228.0,
                top: 624.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 114.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 623.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 115.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 668.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 27.0,
                child: GeneratedNextWidget(),
              ),
              Positioned(
                left: 239.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 43.0,
                child: GeneratedConnectWidget1(),
              ),
              Positioned(
                left: 133.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 114.0,
                child: GeneratedUnknowngirl16Widget1(),
              ),
              Positioned(
                left: 74.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 506.0,
                child: GeneratedMain_Background1Widget1(),
              ),
              Positioned(
                left: 74.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 506.0,
                child: GeneratedMain_Background2Widget1(),
              ),
              Positioned(
                left: 29.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 46.0,
                child: GeneratedRectangle22Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 24.0,
                child: GeneratedExperienceWidget(),
              ),
              Positioned(
                left: 84.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 16.0,
                child: GeneratedSoftwareEngineerAmazonWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 27.0,
                child: Generated2019presentWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 46.0,
                child: GeneratedRectangle22Widget1(),
              ),
              Positioned(
                left: 29.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 24.0,
                child: GeneratedEducationWidget2(),
              ),
              Positioned(
                left: 123.0,
                top: 425.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 20.0,
                child: GeneratedPurdueUniversityWidget(),
              ),
              Positioned(
                left: 84.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 27.0,
                child: Generated20142018BachelorinComputerScienceWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 206.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 109.0,
                child:
                    GeneratedHithisisSarahIhavebecomeateachingassistanceonCSsincecol(),
              ),
              Positioned(
                left: 113.0,
                top: 715.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 52.0,
                child: GeneratedGroup3Widget(),
              )
            ]),
      ),
    ));
  }
}
