import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu9.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedDontConnectWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedConnectWidget3.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedExperienceWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedNewlogo_31Widget4.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedSeniorSoftwareDeveloperApple20152017Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedFrontEndExecutiveGoldmanSachs2018presentWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedSarahTWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedEllipse2Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio2widget/generated/GeneratedUnknowngirl16Widget.dart';

/* Frame mentor bio 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMentorbio2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 780.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 233, 229, 214),
                ),
              ),
              Positioned(
                left: 165.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 51.0,
                child: GeneratedNewlogo_31Widget4(),
              ),
              Positioned(
                left: 50.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 65.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu9(),
              ),
              Positioned(
                left: 137.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 28.0,
                child: GeneratedSarahTWidget1(),
              ),
              Positioned(
                left: 2.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 31.0,
                child: GeneratedExperienceWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 25.0,
                child: GeneratedSeniorSoftwareDeveloperApple20152017Widget1(),
              ),
              Positioned(
                left: 24.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 27.0,
                child:
                    GeneratedFrontEndExecutiveGoldmanSachs2018presentWidget1(),
              ),
              Positioned(
                left: 221.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 116.0,
                child: GeneratedEllipse1Widget1(),
              ),
              Positioned(
                left: 27.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 115.0,
                child: GeneratedEllipse2Widget1(),
              ),
              Positioned(
                left: 58.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 24.0,
                child: GeneratedDontConnectWidget1(),
              ),
              Positioned(
                left: 232.0,
                top: 645.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 38.0,
                child: GeneratedConnectWidget3(),
              ),
              Positioned(
                left: 141.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 114.0,
                child: GeneratedUnknowngirl16Widget(),
              )
            ]),
      ),
    ));
  }
}
