import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupwidget/generated/GeneratedEnteryouremailWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupwidget/generated/GeneratedCreateUsernameWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupwidget/generated/GeneratedEnteryourNameWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupwidget/generated/GeneratedFindPeopleWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupwidget/generated/GeneratedUntitled_Artwork21Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupwidget/generated/GeneratedCreateAccountWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupwidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupwidget/generated/GeneratedLetsfindyouamentorOrPerhapssomefriendsWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupwidget/generated/GeneratedCreatePasswordWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupwidget/generated/GeneratedUntitled_Artwork2Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupwidget/generated/GeneratedRectangle4Widget.dart';

/* Frame Signup
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 815.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 16, 104, 135),
                  ),
                ),
                Positioned(
                  left: -11.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 397.0,
                  height: 815.0,
                  child: GeneratedUntitled_Artwork21Widget(),
                ),
                Positioned(
                  left: 90.12313842773438,
                  top: 668.0,
                  right: null,
                  bottom: null,
                  width: 213.00889587402344,
                  height: 30.968994140625,
                  child: GeneratedRectangle1Widget(),
                ),
                Positioned(
                  left: 88.14471435546875,
                  top: 534.0,
                  right: null,
                  bottom: null,
                  width: 232.8376007080078,
                  height: 32.97874450683594,
                  child: GeneratedRectangle3Widget(),
                ),
                Positioned(
                  left: 88.14468383789062,
                  top: 578.0,
                  right: null,
                  bottom: null,
                  width: 232.8376007080078,
                  height: 32.97874450683594,
                  child: GeneratedRectangle4Widget(),
                ),
                Positioned(
                  left: 153.0,
                  top: 675.0,
                  right: null,
                  bottom: null,
                  width: 89.0,
                  height: 21.0,
                  child: GeneratedCreateAccountWidget(),
                ),
                Positioned(
                  left: 134.0,
                  top: 323.0,
                  right: null,
                  bottom: null,
                  width: 143.0,
                  height: 38.0,
                  child: GeneratedFindPeopleWidget(),
                ),
                Positioned(
                  left: 32.0,
                  top: 367.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 46.0,
                  child:
                      GeneratedLetsfindyouamentorOrPerhapssomefriendsWidget(),
                ),
                Positioned(
                  left: 150.0,
                  top: 544.0,
                  right: null,
                  bottom: null,
                  width: 112.0,
                  height: 20.0,
                  child: GeneratedCreateUsernameWidget(),
                ),
                Positioned(
                  left: 150.0,
                  top: 586.0,
                  right: null,
                  bottom: null,
                  width: 112.0,
                  height: 20.0,
                  child: GeneratedCreatePasswordWidget(),
                ),
                Positioned(
                  left: 88.14472961425781,
                  top: 441.0,
                  right: null,
                  bottom: null,
                  width: 232.8376007080078,
                  height: 32.97874450683594,
                  child: GeneratedRectangle5Widget(),
                ),
                Positioned(
                  left: 88.14469909667969,
                  top: 485.0,
                  right: null,
                  bottom: null,
                  width: 232.8376007080078,
                  height: 32.97874450683594,
                  child: GeneratedRectangle6Widget(),
                ),
                Positioned(
                  left: 150.00001525878906,
                  top: 451.0,
                  right: null,
                  bottom: null,
                  width: 112.0,
                  height: 20.0,
                  child: GeneratedEnteryourNameWidget(),
                ),
                Positioned(
                  left: 150.00001525878906,
                  top: 493.0,
                  right: null,
                  bottom: null,
                  width: 112.0,
                  height: 20.0,
                  child: GeneratedEnteryouremailWidget(),
                ),
                Positioned(
                  left: 76.0,
                  top: 64.0,
                  right: null,
                  bottom: null,
                  width: 239.0,
                  height: 239.0,
                  child: GeneratedUntitled_Artwork2Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
