import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedUntitled_Artwork21Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedImmediateConnectwithMentorsMenteesWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedLetsfindyouamentorPerhapssomefriendsWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedCreatePasswordWidget2.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedUntitled_Artwork1Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedUsernameorEmailWidget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedSignUpWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedUntitled_Artwork31Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedRectangle4Widget2.dart';

/* Frame HomePage
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 780.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -18.0,
                  top: -35.0,
                  right: null,
                  bottom: null,
                  width: 397.0,
                  height: 815.0,
                  child: GeneratedUntitled_Artwork21Widget2(),
                ),
                Positioned(
                  left: 48.0,
                  top: 455.0,
                  right: null,
                  bottom: null,
                  width: 283.0,
                  height: 154.0,
                  child: GeneratedRectangle7Widget(),
                ),
                Positioned(
                  left: 128.4622802734375,
                  top: 581.0,
                  right: null,
                  bottom: null,
                  width: 104.53874969482422,
                  height: 29.291933059692383,
                  child: GeneratedRectangle1Widget2(),
                ),
                Positioned(
                  left: 47.18145751953125,
                  top: 520.35595703125,
                  right: null,
                  bottom: null,
                  width: 292.0335998535156,
                  height: 41.3631706237793,
                  child: GeneratedRectangle4Widget2(),
                ),
                Positioned(
                  left: 126.13580322265625,
                  top: 645.0,
                  right: null,
                  bottom: null,
                  width: 104.53874969482422,
                  height: 31.532968521118164,
                  child: GeneratedRectangle2Widget(),
                ),
                Positioned(
                  left: 164.0,
                  top: 589.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 23.0,
                  child: GeneratedLoginWidget(),
                ),
                Positioned(
                  left: 158.0,
                  top: 651.0,
                  right: null,
                  bottom: null,
                  width: 46.0,
                  height: 20.0,
                  child: GeneratedSignUpWidget(),
                ),
                Positioned(
                  left: 8.0,
                  top: 392.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 53.0,
                  child: GeneratedLetsfindyouamentorPerhapssomefriendsWidget(),
                ),
                Positioned(
                  left: 81.0,
                  top: 350.0,
                  right: null,
                  bottom: null,
                  width: 218.0,
                  height: 48.0,
                  child: GeneratedImmediateConnectwithMentorsMenteesWidget1(),
                ),
                Positioned(
                  left: 47.99993896484375,
                  top: 415.0,
                  right: null,
                  bottom: null,
                  width: 241.0,
                  height: 32.0,
                  child: GeneratedUsernameorEmailWidget(),
                ),
                Positioned(
                  left: 47.99993896484375,
                  top: 498.0,
                  right: null,
                  bottom: null,
                  width: 140.0,
                  height: 24.0,
                  child: GeneratedCreatePasswordWidget2(),
                ),
                Positioned(
                  left: 63.0,
                  top: 32.0,
                  right: null,
                  bottom: null,
                  width: 239.0,
                  height: 239.0,
                  child: GeneratedUntitled_Artwork1Widget1(),
                ),
                Positioned(
                  left: 65.0,
                  top: 271.0,
                  right: null,
                  bottom: null,
                  width: 249.0,
                  height: 104.0,
                  child: GeneratedUntitled_Artwork31Widget(),
                ),
                Positioned(
                  left: 48.18145751953125,
                  top: 437.0,
                  right: null,
                  bottom: null,
                  width: 292.0335998535156,
                  height: 41.3631706237793,
                  child: GeneratedRectangle3Widget2(),
                )
              ]),
        ),
      ),
    ));
  }
}
