import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedRectangle3Widget3.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedImmediateConnectwithMentorsMenteesWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedUntitled_Artwork1Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedUntitled_Artwork31Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedLetsfindyouamentorPerhapssomefriendsWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedUsernameorEmailWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedCreatePasswordWidget2.dart';
import 'package:flutterapp/uni_careerapp/generatedhomepagewidget/generated/GeneratedRectangle7Widget.dart';

/* Frame HomePage
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 780.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Image.asset(
                    "assets/images/ace213ea1e1df25a8458334ae61b2a9bf0914c05.png",
                    color: null,
                    fit: BoxFit.cover,
                    width: 360.0,
                    height: 780.0,
                    colorBlendMode: BlendMode.dstATop,
                  ),
                ),
                Positioned(
                  left: 48.0,
                  top: 455.0,
                  right: null,
                  bottom: null,
                  width: 283.0,
                  height: 154.0,
                  child: GeneratedRectangle7Widget(),
                ),
                Positioned(
                  left: 47.18145751953125,
                  top: 520.35595703125,
                  right: null,
                  bottom: null,
                  width: 292.0335998535156,
                  height: 41.3631706237793,
                  child: GeneratedRectangle4Widget2(),
                ),
                Positioned(
                  left: 129.33480834960938,
                  top: 591.0,
                  right: null,
                  bottom: null,
                  width: 104.66519927978516,
                  height: 29.754104614257812,
                  child: GeneratedGroup18Widget(),
                ),
                Positioned(
                  left: 128.00001525878906,
                  top: 643.0,
                  right: null,
                  bottom: null,
                  width: 104.67350006103516,
                  height: 31.99999237060547,
                  child: GeneratedGroup17Widget(),
                ),
                Positioned(
                  left: 8.0,
                  top: 392.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 53.0,
                  child: GeneratedLetsfindyouamentorPerhapssomefriendsWidget(),
                ),
                Positioned(
                  left: 81.0,
                  top: 350.0,
                  right: null,
                  bottom: null,
                  width: 218.0,
                  height: 48.0,
                  child: GeneratedImmediateConnectwithMentorsMenteesWidget1(),
                ),
                Positioned(
                  left: 47.99993896484375,
                  top: 415.0,
                  right: null,
                  bottom: null,
                  width: 241.0,
                  height: 32.0,
                  child: GeneratedUsernameorEmailWidget(),
                ),
                Positioned(
                  left: 47.99993896484375,
                  top: 498.0,
                  right: null,
                  bottom: null,
                  width: 140.0,
                  height: 24.0,
                  child: GeneratedCreatePasswordWidget2(),
                ),
                Positioned(
                  left: 63.0,
                  top: 32.0,
                  right: null,
                  bottom: null,
                  width: 239.0,
                  height: 239.0,
                  child: GeneratedUntitled_Artwork1Widget1(),
                ),
                Positioned(
                  left: 65.0,
                  top: 271.0,
                  right: null,
                  bottom: null,
                  width: 249.0,
                  height: 104.0,
                  child: GeneratedUntitled_Artwork31Widget(),
                ),
                Positioned(
                  left: 48.18145751953125,
                  top: 437.0,
                  right: null,
                  bottom: null,
                  width: 292.0335998535156,
                  height: 41.3631706237793,
                  child: GeneratedRectangle3Widget3(),
                ),
                Positioned(
                  left: 113.0,
                  top: 692.0,
                  right: null,
                  bottom: null,
                  width: 147.0,
                  height: 26.0,
                  child: GeneratedGroup5Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
