import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedCreateUsernameWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedIPhoneKeyboard1Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedUniCareer1Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedEnterNameWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedUntitled_Artwork1Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedSignUp31Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedRectangle5Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedSignUp31Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedIagreewiththePrivacyPolicyWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedLetsfindyouamentorOrPerhapssomefriendsWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedEnterEmailWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedSignUp31Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedCreatePasswordWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedsignupnologowidget/generated/GeneratedRectangle8Widget.dart';

/* Frame Signup - no Logo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupnoLogoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 780.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/ace213ea1e1df25a8458334ae61b2a9bf0914c05.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 360.0,
                  height: 780.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 36.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 33.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 31.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 76.14469909667969,
                top: 326.0,
                right: null,
                bottom: null,
                width: 232.8376007080078,
                height: 32.97874450683594,
                child: GeneratedRectangle3Widget2(),
              ),
              Positioned(
                left: 78.14469909667969,
                top: 381.0,
                right: null,
                bottom: null,
                width: 232.8376007080078,
                height: 32.97874450683594,
                child: GeneratedRectangle4Widget1(),
              ),
              Positioned(
                left: 85.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 213.12954711914062,
                height: 32.0,
                child: GeneratedGroup19Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedLetsfindyouamentorOrPerhapssomefriendsWidget1(),
              ),
              Positioned(
                left: 78.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 20.0,
                child: GeneratedCreateUsernameWidget1(),
              ),
              Positioned(
                left: 78.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 20.0,
                child: GeneratedCreatePasswordWidget1(),
              ),
              Positioned(
                left: 76.14472961425781,
                top: 203.0,
                right: null,
                bottom: null,
                width: 232.8376007080078,
                height: 32.97874450683594,
                child: GeneratedRectangle5Widget1(),
              ),
              Positioned(
                left: 76.14469909667969,
                top: 264.0,
                right: null,
                bottom: null,
                width: 232.8376007080078,
                height: 32.97874450683594,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 78.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 20.0,
                child: GeneratedEnterNameWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 20.0,
                child: GeneratedEnterEmailWidget(),
              ),
              Positioned(
                left: -11.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 152.0,
                child: GeneratedSignUp31Widget(),
              ),
              Positioned(
                left: -17.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 392.0,
                height: 176.0,
                child: GeneratedSignUp31Widget1(),
              ),
              Positioned(
                left: 23.0,
                top: -3.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 142.0,
                child: GeneratedSignUp31Widget2(),
              ),
              Positioned(
                left: 163.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 47.0,
                child: GeneratedUntitled_Artwork1Widget(),
              ),
              Positioned(
                left: 80.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 109.0,
                child: GeneratedUniCareer1Widget(),
              ),
              Positioned(
                left: 109.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 16.0,
                child: GeneratedIagreewiththePrivacyPolicyWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 250.0,
                child: GeneratedIPhoneKeyboard1Widget(),
              )
            ]),
      ),
    ));
  }
}
