import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedEducationWidget3.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedHealthphoto2Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedCommunicationsWidget3.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedNoteSubmittoHomepageWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedNewlogo_31Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedProgrammingimage4Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedPhoneWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedRectangle17Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedRectangle15Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedBusinessWidget3.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedLocationWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedChangeYourInterestWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedWidget2.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedFinancephoto6Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedLv1MenteeWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedUnknownpersonicon42Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedBioWidget3.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedRectangle19Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedBioWidget2.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedTradesWidget3.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedProgrammingimage3Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedEmailWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedHealthScienceWidget3.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedRectangle14Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedEducationphoto2Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedRectangle18Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedTechnologyWidget3.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedFinancephoto5Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentortellusaboutyourselffrommainpagewidget/generated/GeneratedUpdateyourinformationWidget1.dart';

/* Frame (Mentor) Tell us about yourself - from Main Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMentorTellusaboutyourselffromMainPageWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 780.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 233, 229, 214),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 293.0,
                child: GeneratedRectangle13Widget1(),
              ),
              Positioned(
                left: 151.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 51.0,
                child: GeneratedNewlogo_31Widget2(),
              ),
              Positioned(
                left: 32.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 21.0,
                child: GeneratedChangeYourInterestWidget1(),
              ),
              Positioned(
                left: 33.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 21.0,
                child: GeneratedBioWidget2(),
              ),
              Positioned(
                left: 31.0,
                top: 511.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 17.0,
                child: GeneratedTechnologyWidget3(),
              ),
              Positioned(
                left: 247.0,
                top: 511.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 29.0,
                child: GeneratedEducationWidget3(),
              ),
              Positioned(
                left: 48.0079345703125,
                top: 442.0,
                right: null,
                bottom: null,
                width: 55.104434967041016,
                height: 57.50311279296875,
                child: GeneratedProgrammingimage3Widget1(),
              ),
              Positioned(
                left: 44.0079345703125,
                top: 570.0,
                right: null,
                bottom: null,
                width: 55.104434967041016,
                height: 57.50311279296875,
                child: GeneratedProgrammingimage4Widget1(),
              ),
              Positioned(
                left: null,
                top: 511.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 29.0,
                child: TransformHelper.translate(
                    x: 5.50, y: 0.00, z: 0, child: GeneratedBusinessWidget3()),
              ),
              Positioned(
                left: 160.0,
                top: 441.6124267578125,
                right: null,
                bottom: null,
                width: 55.07784652709961,
                height: 57.45728302001953,
                child: GeneratedFinancephoto5Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 632.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 17.0,
                child: GeneratedTradesWidget3(),
              ),
              Positioned(
                left: 238.0,
                top: 643.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 33.0,
                child: GeneratedCommunicationsWidget3(),
              ),
              Positioned(
                left: null,
                top: 639.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: -5.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedHealthScienceWidget3()),
              ),
              Positioned(
                left: 251.0,
                top: 580.6123046875,
                right: null,
                bottom: null,
                width: 55.07784652709961,
                height: 57.45728302001953,
                child: GeneratedFinancephoto6Widget1(),
              ),
              Positioned(
                left: 156.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 56.0,
                child: GeneratedHealthphoto2Widget1(),
              ),
              Positioned(
                left: 255.0,
                top: 442.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 58.0,
                child: GeneratedEducationphoto2Widget1(),
              ),
              Positioned(
                left: 151.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 21.0,
                child: GeneratedRectangle12Widget1(),
              ),
              Positioned(
                left: 33.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 21.0,
                child: GeneratedBioWidget3(),
              ),
              Positioned(
                left: 151.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 21.0,
                child: GeneratedRectangle15Widget2(),
              ),
              Positioned(
                left: 32.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 24.0,
                child: GeneratedLocationWidget1(),
              ),
              Positioned(
                left: 150.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 21.0,
                child: GeneratedRectangle14Widget2(),
              ),
              Positioned(
                left: 33.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 24.0,
                child: GeneratedPhoneWidget1(),
              ),
              Positioned(
                left: 151.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 21.0,
                child: GeneratedRectangle17Widget1(),
              ),
              Positioned(
                left: 151.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 21.0,
                child: GeneratedRectangle18Widget1(),
              ),
              Positioned(
                left: 32.0,
                top: 357.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 24.0,
                child: GeneratedEmailWidget1(),
              ),
              Positioned(
                left: 150.0,
                top: 355.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 21.0,
                child: GeneratedRectangle19Widget1(),
              ),
              Positioned(
                left: 211.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 24.0,
                child: GeneratedNoteSubmittoHomepageWidget(),
              ),
              Positioned(
                left: -4.0,
                top: -3.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 221.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 118.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 110.0,
                child: GeneratedUnknownpersonicon42Widget(),
              ),
              Positioned(
                left: 106.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 65.0,
                child: GeneratedUpdateyourinformationWidget1(),
              ),
              Positioned(
                left: 210.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 26.0,
                child: GeneratedWidget2(),
              ),
              Positioned(
                left: 90.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 21.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 143.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 18.0,
                child: GeneratedLv1MenteeWidget1(),
              )
            ]),
      ),
    ));
  }
}
