import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedSeniorSoftwareDeveloperApple20152017Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedExperienceWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedRelatedWorkWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedUnknownboy12Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedGithubMattAWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedDontConnectWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedFrontEndExecutiveGoldmanSachs2018presentWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu8.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedNewlogo_31Widget3.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedDukeUniversity20092013Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedMattAWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedEducationWidget5.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedConnectWidget2.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedEllipse2Widget.dart';

/* Frame mentor bio 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMentorbio1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 780.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 233, 229, 214),
                ),
              ),
              Positioned(
                left: 159.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 51.0,
                child: GeneratedNewlogo_31Widget3(),
              ),
              Positioned(
                left: 137.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 114.0,
                child: GeneratedUnknownboy12Widget1(),
              ),
              Positioned(
                left: 50.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 65.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu8(),
              ),
              Positioned(
                left: 137.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 19.0,
                child: GeneratedMattAWidget1(),
              ),
              Positioned(
                left: 2.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 31.0,
                child: GeneratedExperienceWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 25.0,
                child: GeneratedSeniorSoftwareDeveloperApple20152017Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 27.0,
                child:
                    GeneratedFrontEndExecutiveGoldmanSachs2018presentWidget(),
              ),
              Positioned(
                left: 215.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 116.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 115.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 639.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 24.0,
                child: GeneratedDontConnectWidget(),
              ),
              Positioned(
                left: 226.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 38.0,
                child: GeneratedConnectWidget2(),
              ),
              Positioned(
                left: 10.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 47.0,
                child: GeneratedEducationWidget5(),
              ),
              Positioned(
                left: -10.0,
                top: 428.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 31.0,
                child: GeneratedDukeUniversity20092013Widget(),
              ),
              Positioned(
                left: -12.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 49.0,
                child: GeneratedRelatedWorkWidget(),
              ),
              Positioned(
                left: -12.0,
                top: 496.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 37.0,
                child: GeneratedGithubMattAWidget(),
              )
            ]),
      ),
    ));
  }
}
