import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedProgrammingWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedMain_Background2Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedRectangle36Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedRectangle38Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/Generated20152017Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedUnknowngirl16Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/Generated2018presentWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedRectangle22Widget3.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedMain_Background1Widget3.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedConnectWidget2.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedMattAWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedMattisHereIamexperiencedwithJavaandopenforanystudentsWe.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedNextWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedFocusWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedEducationWidget3.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedMain_Background1Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedMain_Background2Widget3.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedDukeUniversityWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedUntitled_Artwork21Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedSeniorSoftwareDeveloperAppleWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedEllipse2Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedFrontEndExecutiveGoldmanSachsWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedRectangle22Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/Generated20092013BachelorinEECSWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmentorbio1widget/generated/GeneratedExperienceWidget1.dart';

/* Frame mentor bio 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMentorbio1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 780.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -34.0,
                top: -69.0,
                right: null,
                bottom: null,
                width: 397.0,
                height: 933.0,
                child: GeneratedUntitled_Artwork21Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 506.0,
                child: GeneratedMain_Background1Widget2(),
              ),
              Positioned(
                left: 223.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 71.0,
                child: GeneratedRectangle38Widget1(),
              ),
              Positioned(
                left: 34.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 24.0,
                child: GeneratedFocusWidget1(),
              ),
              Positioned(
                left: 49.0,
                top: 547.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 21.0,
                child: GeneratedRectangle36Widget1(),
              ),
              Positioned(
                left: 58.0,
                top: 549.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 19.0,
                child: GeneratedProgrammingWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 506.0,
                child: GeneratedMain_Background2Widget2(),
              ),
              Positioned(
                left: 139.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 28.0,
                child: GeneratedMattAWidget(),
              ),
              Positioned(
                left: 228.0,
                top: 624.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 114.0,
                child: GeneratedEllipse1Widget1(),
              ),
              Positioned(
                left: 7.0,
                top: 623.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 115.0,
                child: GeneratedEllipse2Widget1(),
              ),
              Positioned(
                left: 38.0,
                top: 668.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 27.0,
                child: GeneratedNextWidget1(),
              ),
              Positioned(
                left: 239.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 43.0,
                child: GeneratedConnectWidget2(),
              ),
              Positioned(
                left: 133.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 114.0,
                child: GeneratedUnknowngirl16Widget2(),
              ),
              Positioned(
                left: 74.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 506.0,
                child: GeneratedMain_Background1Widget3(),
              ),
              Positioned(
                left: 74.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 506.0,
                child: GeneratedMain_Background2Widget3(),
              ),
              Positioned(
                left: 29.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 83.0,
                child: GeneratedRectangle22Widget2(),
              ),
              Positioned(
                left: 75.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 217.0,
                height: 16.0,
                child: GeneratedSeniorSoftwareDeveloperAppleWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 27.0,
                child: Generated20152017Widget(),
              ),
              Positioned(
                left: 71.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 16.0,
                child: GeneratedFrontEndExecutiveGoldmanSachsWidget(),
              ),
              Positioned(
                left: 95.0,
                top: 411.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 27.0,
                child: Generated2018presentWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 24.0,
                child: GeneratedExperienceWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 46.0,
                child: GeneratedRectangle22Widget3(),
              ),
              Positioned(
                left: 29.0,
                top: 436.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 24.0,
                child: GeneratedEducationWidget3(),
              ),
              Positioned(
                left: 123.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 20.0,
                child: GeneratedDukeUniversityWidget(),
              ),
              Positioned(
                left: 84.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 27.0,
                child: Generated20092013BachelorinEECSWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 206.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 109.0,
                child:
                    GeneratedMattisHereIamexperiencedwithJavaandopenforanystudentsWe(),
              ),
              Positioned(
                left: 113.0,
                top: 715.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 52.0,
                child: GeneratedGroup3Widget1(),
              )
            ]),
      ),
    ));
  }
}
