import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedSarahTWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedIPhoneKeyboard2Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedHiWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedRectangle85Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedRectangle88Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedUntitled_Artwork21Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedNewlogo_34Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedRectangle93Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedThatsgreatWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedUnknowngirl16Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedRectangle92Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedRectangle87Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedRectangle84Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedDoyoupreferonlineorinpersonWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedRectangle90Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedBackWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedRectangle89Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedRectangle86Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedNewlogo_33Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedOnlinepleaseWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedNewlogo_32Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedHelloWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedmenteementorchatwidget/generated/GeneratedNewlogo_35Widget.dart';

/* Frame Mentee/Mentor Chat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenteeMentorChatWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 780.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 233, 229, 214),
                ),
              ),
              Positioned(
                left: -19.0,
                top: -26.0,
                right: null,
                bottom: null,
                width: 397.0,
                height: 933.0,
                child: GeneratedUntitled_Artwork21Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 378.0,
                height: 590.0,
                child: GeneratedRectangle85Widget(),
              ),
              Positioned(
                left: 272.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 64.0,
                child: GeneratedNewlogo_33Widget(),
              ),
              Positioned(
                left: 277.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 51.0,
                child: GeneratedNewlogo_32Widget1(),
              ),
              Positioned(
                left: 283.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 26.0,
                child: GeneratedBackWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 67.0,
                child: GeneratedUnknowngirl16Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 336.0,
                child: GeneratedRectangle84Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 34.0,
                child: GeneratedRectangle92Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 288.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 23.0,
                child: GeneratedThatsgreatWidget(),
              ),
              Positioned(
                left: 212.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 34.0,
                child: GeneratedRectangle93Widget(),
              ),
              Positioned(
                left: 220.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 23.0,
                child: GeneratedOnlinepleaseWidget(),
              ),
              Positioned(
                left: 269.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 34.0,
                child: GeneratedRectangle90Widget(),
              ),
              Positioned(
                left: 277.0,
                top: 167.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 26.0,
                child: GeneratedHiWidget(),
              ),
              Positioned(
                left: 11.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 64.0,
                child: GeneratedRectangle89Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 44.0,
                child: GeneratedDoyoupreferonlineorinpersonWidget(),
              ),
              Positioned(
                left: 159.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 64.0,
                child: GeneratedGroup16Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 467.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 42.0,
                child: GeneratedRectangle87Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 32.0,
                child: GeneratedRectangle86Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 27.0,
                child: GeneratedNewlogo_35Widget(),
              ),
              Positioned(
                left: 315.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 27.0,
                child: GeneratedNewlogo_34Widget(),
              ),
              Positioned(
                left: 91.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 28.0,
                child: GeneratedSarahTWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 34.0,
                child: GeneratedRectangle88Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 26.0,
                child: GeneratedHelloWidget(),
              ),
              Positioned(
                left: 57.40673828125,
                top: 500.9967041015625,
                right: null,
                bottom: null,
                width: 25.0,
                height: 1.0,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 250.0,
                child: GeneratedIPhoneKeyboard2Widget(),
              )
            ]),
      ),
    ));
  }
}
