import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedexploremorewidget/generated/GeneratedGroup24Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedexploremorewidget/generated/GeneratedRectangle95Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedexploremorewidget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedexploremorewidget/generated/GeneratedNewlogo_36Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedexploremorewidget/generated/GeneratedRectangle58Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedexploremorewidget/generated/GeneratedGroup26Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedexploremorewidget/generated/GeneratedExploreMoreWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedexploremorewidget/generated/GeneratedProgrammingWidget5.dart';
import 'package:flutterapp/uni_careerapp/generatedexploremorewidget/generated/GeneratedRectangle94Widget.dart';

/* Frame Explore More
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExploreMoreWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 780.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/ace213ea1e1df25a8458334ae61b2a9bf0914c05.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 360.0,
                  height: 780.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 12.0,
                top: 28.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 657.0,
                child: GeneratedRectangle94Widget(),
              ),
              Positioned(
                left: 323.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 19.0,
                height: 635.0,
                child: GeneratedGroup21Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 21.0,
                child: GeneratedProgrammingWidget5(),
              ),
              Positioned(
                left: 21.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 126.0,
                child: GeneratedRectangle58Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 545.0,
                child: GeneratedGroup24Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 39.0,
                child: GeneratedRectangle95Widget(),
              ),
              Positioned(
                left: 88.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 21.0,
                child: GeneratedExploreMoreWidget1(),
              ),
              Positioned(
                left: 149.0,
                top: 702.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 64.0,
                child: GeneratedNewlogo_36Widget(),
              ),
              Positioned(
                left: 120.0,
                top: 708.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 51.0,
                child: GeneratedGroup26Widget(),
              )
            ]),
      ),
    ));
  }
}
