import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedswipewidget/generated/GeneratedTechnologyWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/uni_careerapp/generatedswipewidget/generated/GeneratedConnectWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedswipewidget/generated/GeneratedNewlogo_32Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedswipewidget/generated/GeneratedLawWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedswipewidget/generated/GeneratedCommunicationsWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedswipewidget/generated/GeneratedEducationWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedswipewidget/generated/GeneratedTradesWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedswipewidget/generated/GeneratedHealthphoto1Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedswipewidget/generated/GeneratedGovernmentWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedswipewidget/generated/GeneratedBusinessWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedswipewidget/generated/GeneratedHealthScienceWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedswipewidget/generated/GeneratedProgrammingimage2Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedswipewidget/generated/GeneratedPsychologyWidget1.dart';

/* Frame Swipe
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSwipeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 815.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 16, 104, 135),
                  ),
                ),
                Positioned(
                  left: 144.0,
                  top: 721.0,
                  right: null,
                  bottom: null,
                  width: 81.0,
                  height: 31.0,
                  child: GeneratedConnectWidget1(),
                ),
                Positioned(
                  left: 4.0,
                  top: 53.0,
                  right: null,
                  bottom: null,
                  width: 104.0,
                  height: 25.0,
                  child: GeneratedTechnologyWidget1(),
                ),
                Positioned(
                  left: 292.0,
                  top: 54.0,
                  right: null,
                  bottom: null,
                  width: 78.0,
                  height: 26.0,
                  child: GeneratedEducationWidget1(),
                ),
                Positioned(
                  left: null,
                  top: 54.0,
                  right: null,
                  bottom: null,
                  width: 81.0,
                  height: 26.0,
                  child: TransformHelper.translate(
                      x: 4.00,
                      y: 0.00,
                      z: 0,
                      child: GeneratedBusinessWidget1()),
                ),
                Positioned(
                  left: 0.0,
                  top: 253.0,
                  right: null,
                  bottom: null,
                  width: 104.0,
                  height: 25.0,
                  child: GeneratedTradesWidget1(),
                ),
                Positioned(
                  left: 247.0,
                  top: 253.0,
                  right: null,
                  bottom: null,
                  width: 127.0,
                  height: 20.0,
                  child: GeneratedCommunicationsWidget1(),
                ),
                Positioned(
                  left: null,
                  top: 252.0,
                  right: null,
                  bottom: null,
                  width: 122.0,
                  height: 37.0,
                  child: TransformHelper.translate(
                      x: -3.50,
                      y: 0.00,
                      z: 0,
                      child: GeneratedHealthScienceWidget1()),
                ),
                Positioned(
                  left: 4.0,
                  top: 442.0,
                  right: null,
                  bottom: null,
                  width: 104.0,
                  height: 25.0,
                  child: GeneratedGovernmentWidget1(),
                ),
                Positioned(
                  left: 240.0,
                  top: 442.0,
                  right: null,
                  bottom: null,
                  width: 127.0,
                  height: 20.0,
                  child: GeneratedPsychologyWidget1(),
                ),
                Positioned(
                  left: null,
                  top: 443.0,
                  right: null,
                  bottom: null,
                  width: 83.0,
                  height: 44.0,
                  child: TransformHelper.translate(
                      x: 5.00, y: 0.00, z: 0, child: GeneratedLawWidget1()),
                ),
                Positioned(
                  left: 4.013275146484375,
                  top: 284.0,
                  right: null,
                  bottom: null,
                  width: 91.9836654663086,
                  height: 95.98768615722656,
                  child: GeneratedProgrammingimage2Widget1(),
                ),
                Positioned(
                  left: 147.0,
                  top: 286.0,
                  right: null,
                  bottom: null,
                  width: 92.0,
                  height: 95.0,
                  child: GeneratedHealthphoto1Widget1(),
                ),
                Positioned(
                  left: 152.0,
                  top: 749.0,
                  right: null,
                  bottom: null,
                  width: 59.0,
                  height: 59.0,
                  child: GeneratedNewlogo_32Widget1(),
                )
              ]),
        ),
      ),
    ));
  }
}
