import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedHenryAWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu4.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu7.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu3.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu5.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedDaleOWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedUnknownboy13Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedUnknownboy15Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedLuisHWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu1.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu2.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedNewlogo_32Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedUnknowngirl12Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedUnknownboy12Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedZihanXWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu6.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedMattAWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedSusiePWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedMyConnectionsWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedKennyAWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedUnknownboy14Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedUnknowngirl13Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedSarahTWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedUnknowngirl15Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedcurrentconnectionwidget/generated/GeneratedUnknowngirl14Widget.dart';

/* Frame Current Connection
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCurrentConnectionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 780.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 233, 229, 214),
                ),
              ),
              Positioned(
                left: 1.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 51.0,
                child: GeneratedUnknownboy12Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 51.0,
                child: GeneratedUnknowngirl12Widget(),
              ),
              Positioned(
                left: 72.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 65.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu(),
              ),
              Positioned(
                left: 72.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 45.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu1(),
              ),
              Positioned(
                left: 1.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 18.0,
                child: GeneratedMattAWidget(),
              ),
              Positioned(
                left: 1.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 18.0,
                child: GeneratedSarahTWidget(),
              ),
              Positioned(
                left: 1.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 51.0,
                child: GeneratedUnknownboy13Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 51.0,
                child: GeneratedUnknowngirl13Widget(),
              ),
              Positioned(
                left: 72.0,
                top: 235.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 65.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu2(),
              ),
              Positioned(
                left: 72.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 45.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu3(),
              ),
              Positioned(
                left: 1.0,
                top: 282.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 18.0,
                child: GeneratedHenryAWidget(),
              ),
              Positioned(
                left: 1.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 18.0,
                child: GeneratedDaleOWidget(),
              ),
              Positioned(
                left: 1.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 51.0,
                child: GeneratedUnknownboy14Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 51.0,
                child: GeneratedUnknowngirl14Widget(),
              ),
              Positioned(
                left: 72.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 65.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu4(),
              ),
              Positioned(
                left: 72.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 45.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu5(),
              ),
              Positioned(
                left: 1.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 18.0,
                child: GeneratedLuisHWidget(),
              ),
              Positioned(
                left: 1.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 18.0,
                child: GeneratedSusiePWidget(),
              ),
              Positioned(
                left: 1.0,
                top: 543.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 51.0,
                child: GeneratedUnknownboy15Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 51.0,
                child: GeneratedUnknowngirl15Widget(),
              ),
              Positioned(
                left: 72.0,
                top: 547.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 65.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu6(),
              ),
              Positioned(
                left: 66.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 45.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu7(),
              ),
              Positioned(
                left: 0.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 18.0,
                child: GeneratedKennyAWidget(),
              ),
              Positioned(
                left: -3.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 18.0,
                child: GeneratedZihanXWidget(),
              ),
              Positioned(
                left: 167.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 51.0,
                child: GeneratedNewlogo_32Widget2(),
              ),
              Positioned(
                left: 113.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 33.0,
                child: GeneratedMyConnectionsWidget(),
              )
            ]),
      ),
    ));
  }
}
