import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle54Widget4.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle63Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedThisisforMatchingnearyouWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedOtherWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle62Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedMenteeWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedOnlineWidget1.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedUnknownpersonicon41Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedBioWidget6.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedWidget2.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle58Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedWhoareyouWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedPlatformWidget2.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedHowyouprefertoteachlearnWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedCountryWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle64Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedCityWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedTellussomethingaboutyourselfWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedProgrammingWidget4.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle55Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle56Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedMentorWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedChooseYourFocusWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle65Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle61Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedLocationWidget3.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle84Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedInpersonWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle66Widget4.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle60Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedStateWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedStartshereWidget.dart';

/* Frame Tell us about yourself - from Sign Up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTellusaboutyourselffromSignUpWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 780.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 241, 241, 241),
                ),
              ),
              Positioned(
                left: 11.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 541.0,
                child: GeneratedRectangle84Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 214.0,
                child: GeneratedRectangle11Widget1(),
              ),
              Positioned(
                left: 122.0,
                top: 71.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 110.0,
                child: GeneratedUnknownpersonicon41Widget2(),
              ),
              Positioned(
                left: 210.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 26.0,
                child: GeneratedWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 21.0,
                child: GeneratedChooseYourFocusWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 21.0,
                child: GeneratedWhoareyouWidget(),
              ),
              Positioned(
                left: 147.10934448242188,
                top: 736.0,
                right: null,
                bottom: null,
                width: 81.72559356689453,
                height: 24.92129898071289,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 254.10934448242188,
                top: 736.0,
                right: null,
                bottom: null,
                width: 81.72559356689453,
                height: 24.92129898071289,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 160.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 24.0,
                child: GeneratedMentorWidget(),
              ),
              Positioned(
                left: 267.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 24.0,
                child: GeneratedMenteeWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 21.0,
                child: GeneratedBioWidget6(),
              ),
              Positioned(
                left: 27.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 21.0,
                child: GeneratedThisisforMatchingnearyouWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 21.0,
                child: GeneratedTellussomethingaboutyourselfWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 21.0,
                child: GeneratedHowyouprefertoteachlearnWidget(),
              ),
              Positioned(
                left: 133.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 21.0,
                child: GeneratedRectangle55Widget1(),
              ),
              Positioned(
                left: 207.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 21.0,
                child: GeneratedRectangle65Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 24.0,
                child: GeneratedLocationWidget3(),
              ),
              Positioned(
                left: 131.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 204.0,
                height: 46.0,
                child: GeneratedRectangle56Widget1(),
              ),
              Positioned(
                left: 134.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 21.0,
                child: GeneratedStartshereWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 24.0,
                child: GeneratedPlatformWidget2(),
              ),
              Positioned(
                left: 21.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 1.0,
                child: GeneratedRectangle60Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 1.0,
                child: GeneratedRectangle61Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 1.0,
                child: GeneratedRectangle62Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 438.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 290.0,
                child: GeneratedGroup20Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 16.0,
                child: GeneratedProgrammingWidget4(),
              ),
              Positioned(
                left: 30.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 90.0,
                child: GeneratedRectangle54Widget4(),
              ),
              Positioned(
                left: 200.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 22.0,
                child: GeneratedRectangle63Widget(),
              ),
              Positioned(
                left: 133.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 22.0,
                child: GeneratedRectangle58Widget(),
              ),
              Positioned(
                left: 133.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 26.0,
                child: GeneratedOnlineWidget1(),
              ),
              Positioned(
                left: 126.0,
                top: 246.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 19.0,
                child: GeneratedCityWidget(),
              ),
              Positioned(
                left: 201.0,
                top: 246.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 18.0,
                child: GeneratedStateWidget(),
              ),
              Positioned(
                left: 275.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 21.0,
                child: GeneratedRectangle66Widget4(),
              ),
              Positioned(
                left: 274.0,
                top: 246.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 16.0,
                child: GeneratedCountryWidget(),
              ),
              Positioned(
                left: 274.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 22.0,
                child: GeneratedRectangle64Widget(),
              ),
              Positioned(
                left: 275.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 26.0,
                child: GeneratedOtherWidget(),
              ),
              Positioned(
                left: 200.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 26.0,
                child: GeneratedInpersonWidget(),
              )
            ]),
      ),
    ));
  }
}
