import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedIntroduceyourselfWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedBioWidget4.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle16Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedWidget3.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedWhoareyouWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedTradesWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle15Widget3.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle3Widget3.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedBioWidget5.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedProgrammingimage3Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedEducationphoto2Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedCommunicationsWidget4.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedTechnologyWidget4.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedBusinessWidget4.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedHealthphoto2Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle12Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedMentorWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedHealthScienceWidget4.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle13Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedFinancephoto6Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedLocationWidget2.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle14Widget3.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedChooseYourInterestWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedUnknownpersonicon41Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedEducationWidget4.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedFinancephoto5Widget2.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedMenteeWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedtellusaboutyourselffromsignupwidget/generated/GeneratedProgrammingimage4Widget2.dart';

/* Frame Tell us about yourself - from Sign Up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTellusaboutyourselffromSignUpWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 780.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 233, 229, 214),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 293.0,
                child: GeneratedRectangle13Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 221.0,
                child: GeneratedRectangle11Widget1(),
              ),
              Positioned(
                left: 122.0,
                top: 71.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 110.0,
                child: GeneratedUnknownpersonicon41Widget1(),
              ),
              Positioned(
                left: 109.0,
                top: 252.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 65.0,
                child: GeneratedIntroduceyourselfWidget(),
              ),
              Positioned(
                left: 214.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 26.0,
                child: GeneratedWidget3(),
              ),
              Positioned(
                left: 31.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 21.0,
                child: GeneratedChooseYourInterestWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 727.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 21.0,
                child: GeneratedWhoareyouWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 21.0,
                child: GeneratedBioWidget4(),
              ),
              Positioned(
                left: 31.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 17.0,
                child: GeneratedTechnologyWidget4(),
              ),
              Positioned(
                left: 247.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 29.0,
                child: GeneratedEducationWidget4(),
              ),
              Positioned(
                left: 48.00794982910156,
                top: 421.0,
                right: null,
                bottom: null,
                width: 55.104434967041016,
                height: 57.50311279296875,
                child: GeneratedProgrammingimage3Widget2(),
              ),
              Positioned(
                left: 44.00794982910156,
                top: 549.0,
                right: null,
                bottom: null,
                width: 55.104434967041016,
                height: 57.50311279296875,
                child: GeneratedProgrammingimage4Widget2(),
              ),
              Positioned(
                left: null,
                top: 490.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 29.0,
                child: TransformHelper.translate(
                    x: 5.50, y: 0.00, z: 0, child: GeneratedBusinessWidget4()),
              ),
              Positioned(
                left: 160.0,
                top: 420.6123962402344,
                right: null,
                bottom: null,
                width: 55.07784652709961,
                height: 57.45728302001953,
                child: GeneratedFinancephoto5Widget2(),
              ),
              Positioned(
                left: 39.0,
                top: 611.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 17.0,
                child: GeneratedTradesWidget4(),
              ),
              Positioned(
                left: 238.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 33.0,
                child: GeneratedCommunicationsWidget4(),
              ),
              Positioned(
                left: null,
                top: 618.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: -5.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedHealthScienceWidget4()),
              ),
              Positioned(
                left: 251.0,
                top: 559.6123657226562,
                right: null,
                bottom: null,
                width: 55.07784652709961,
                height: 57.45728302001953,
                child: GeneratedFinancephoto6Widget2(),
              ),
              Positioned(
                left: 156.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 56.0,
                child: GeneratedHealthphoto2Widget2(),
              ),
              Positioned(
                left: 255.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 58.0,
                child: GeneratedEducationphoto2Widget2(),
              ),
              Positioned(
                left: 153.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 21.0,
                child: GeneratedRectangle12Widget2(),
              ),
              Positioned(
                left: 35.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 21.0,
                child: GeneratedBioWidget5(),
              ),
              Positioned(
                left: 153.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 21.0,
                child: GeneratedRectangle15Widget3(),
              ),
              Positioned(
                left: 34.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 24.0,
                child: GeneratedLocationWidget2(),
              ),
              Positioned(
                left: 152.0,
                top: 333.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 21.0,
                child: GeneratedRectangle14Widget3(),
              ),
              Positioned(
                left: 145.10934448242188,
                top: 727.0,
                right: null,
                bottom: null,
                width: 81.72559356689453,
                height: 24.92129898071289,
                child: GeneratedRectangle3Widget3(),
              ),
              Positioned(
                left: 252.10934448242188,
                top: 727.0,
                right: null,
                bottom: null,
                width: 81.72559356689453,
                height: 24.92129898071289,
                child: GeneratedRectangle16Widget2(),
              ),
              Positioned(
                left: 158.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 24.0,
                child: GeneratedMentorWidget(),
              ),
              Positioned(
                left: 265.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 24.0,
                child: GeneratedMenteeWidget(),
              )
            ]),
      ),
    ));
  }
}
