import 'package:flutter/material.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedTradesWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedEducationphoto1Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedFinancephoto4Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedProgrammingimage2Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedLawWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedHealthScienceWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedCommunicationsWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedConnectWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedFinancephoto1Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedUniCareer2Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedPsychologyWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedHealthphoto1Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedGovernmentWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedEducationWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedProgrammingimage1Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedImmediateConnectwithMentorsMenteesWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedNextTechTalkGetPreparedforYourNextLeapWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedBusinessWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedNewlogo_32Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedCategoriesWidget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedNewlogo_31Widget.dart';
import 'package:flutterapp/uni_careerapp/generatedloggedinhomepagewithcategorieswidget/generated/GeneratedTechnologyWidget.dart';

/* Frame Logged in Home page (with categories)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoggedinHomepagewithcategoriesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 780.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 16, 104, 135),
                ),
              ),
              Positioned(
                left: 144.0,
                top: 721.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 31.0,
                child: GeneratedConnectWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 22.0,
                child: GeneratedTechnologyWidget(),
              ),
              Positioned(
                left: 270.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 23.0,
                child: GeneratedEducationWidget(),
              ),
              Positioned(
                left: 22.9671630859375,
                top: 408.1596374511719,
                right: null,
                bottom: null,
                width: 80.10784149169922,
                height: 83.59490966796875,
                child: GeneratedProgrammingimage1Widget(),
              ),
              Positioned(
                left: null,
                top: 389.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 23.0,
                child: TransformHelper.translate(
                    x: -4.50, y: 0.00, z: 0, child: GeneratedBusinessWidget()),
              ),
              Positioned(
                left: 140.53759765625,
                top: 409.0498962402344,
                right: null,
                bottom: null,
                width: 80.0691909790039,
                height: 83.52828979492188,
                child: GeneratedFinancephoto1Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 23.0,
                child: GeneratedTradesWidget(),
              ),
              Positioned(
                left: 234.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 23.0,
                child: GeneratedCommunicationsWidget(),
              ),
              Positioned(
                left: null,
                top: 508.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 33.0,
                child: TransformHelper.translate(
                    x: 14.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedHealthScienceWidget()),
              ),
              Positioned(
                left: 22.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 22.0,
                child: GeneratedGovernmentWidget(),
              ),
              Positioned(
                left: 228.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 18.0,
                child: GeneratedPsychologyWidget(),
              ),
              Positioned(
                left: null,
                top: 678.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 39.0,
                child: TransformHelper.translate(
                    x: 14.50, y: 0.00, z: 0, child: GeneratedLawWidget()),
              ),
              Positioned(
                left: 19.0115966796875,
                top: 547.0,
                right: null,
                bottom: null,
                width: 80.10784149169922,
                height: 83.59490966796875,
                child: GeneratedProgrammingimage2Widget(),
              ),
              Positioned(
                left: 264.591552734375,
                top: 543.0662841796875,
                right: null,
                bottom: null,
                width: 80.0691909790039,
                height: 83.52828979492188,
                child: GeneratedFinancephoto4Widget(),
              ),
              Positioned(
                left: 148.0,
                top: 548.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 83.0,
                child: GeneratedHealthphoto1Widget(),
              ),
              Positioned(
                left: 254.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 84.0,
                child: GeneratedEducationphoto1Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 749.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 59.0,
                child: GeneratedNewlogo_32Widget(),
              ),
              Positioned(
                left: 5.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 239.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 367.0,
                height: 35.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 5.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 17.0,
                child: GeneratedNextTechTalkGetPreparedforYourNextLeapWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 347.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 24.0,
                child: GeneratedCategoriesWidget(),
              ),
              Positioned(
                left: 4.0,
                top: -7.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 64.0,
                child: GeneratedUniCareer2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 61.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 154.0,
                top: 724.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 51.0,
                child: GeneratedNewlogo_31Widget(),
              ),
              Positioned(
                left: 155.0,
                top: 7.0,
                right: null,
                bottom: null,
                width: 204.0,
                height: 38.0,
                child: GeneratedImmediateConnectwithMentorsMenteesWidget(),
              )
            ]),
      ),
    ));
  }
}
